---
# ConfigMap - Configuration non sensible
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  namespace: devops
data:
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_NAME: "studentdb"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/studentdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"

---
# Secret - Credentials sensibles (encod√©s en base64)
apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: devops
type: Opaque
data:
  DB_USER: cm9vdA==        # root en base64
  DB_PASSWORD: cm9vdDEyMw== # root123 en base64

---
# Deployment Spring Boot
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: jvvfer/student-management:2.0
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: spring-secret
              key: DB_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: spring-secret
              key: DB_PASSWORD
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"

---
# Service Spring Boot (NodePort)
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: spring-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8089
    nodePort: 30080
